### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by jshawl** [jshawl/gistalt#100]
![](https://dl.dropbox.com/s/qkm1eyua64xkl07/Screenshot%202015-04-14%2007.21.51.png?dl=0)

**Comment by duncangraham** [comment]
hahaha, yea. I'll think about something fun that could go here

**Comment by jshawl** [comment]
Did you see that recent webgl text example? Could be cool

On Tuesday, April 14, 2015, duncangraham notifications@github.com wrote:

> hahaha, yea. I'll think about something fun that could go here
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gistalt/gistalt/issues/100#issuecomment-92924622.

## 

Jesse Shawl
http://jshawl.com

**Comment by duncangraham** [comment]
the cabbibo one? yea that was rad.

Speaking of web gl, which I've wanted to play with for-ev-er we could make the gistalt g 3d in WebGL, have 404 text above it and as you move the mouse the G would spin/rotate

![screen shot 2015-04-15 at 11 22 18 am](https://cloud.githubusercontent.com/assets/865298/7166300/cc6e856e-e361-11e4-93ce-fa283a902ca2.png)

thoughts?
