### ISSUE TITLE
save button behavior on /new is wonky

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#102]
![uhhhh](https://cloud.githubusercontent.com/assets/865298/7144122/30193fd4-e298-11e4-8a65-df1c98a5882e.gif)

I made a change, and the save button started pulsing, and also the loading indicator appeared... I think i know why, but if I was a user this would confuse the hell out of me. I think the pulsing is fine, but the loading indicator is out of place

**Comment by jshawl** [comment]
I can't reproduce this:
![new-102](https://cloud.githubusercontent.com/assets/3824954/7144751/8ab9a4b6-e2b5-11e4-87f2-2d144f8ac765.gif)

**Comment by duncangraham** [comment]
quitting/reopening chrome fixed this

**Comment by duncangraham** [comment]
fuck, no it didn't

**Comment by duncangraham** [comment]
so it now autosaves on a new gist change, but I'd argue this isn't good. We should let the user decide when to save their gist.

what if it autosaves a gist I meant to be private, but I hadn't checked the box yet-- after saving there isn't a way to check the box
