### ISSUE TITLE
add rendered markdown option.

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#104]
this option should allow you to continue writing, with inline editing https://github.com/gistalt/gistalt/issues/4

I think this is fairly important. it will let non technical folks ease into markdown, and will let people view the output.

I think we should track how many gists are made in each mode. It would be interesting to see what people prefer.

this should be a toggle on the bottom, like the public/private button (https://github.com/gistalt/gistalt/issues/49#issuecomment-92021125)

**Comment by duncangraham** [comment]
After getting feedback from a few people, this should be considered a blocker from showing more folks.

**Comment by duncangraham** [comment]
there should also be a keyboard shortcut so users don't have to stop typing to toggle

**Comment by jshawl** [comment]
I think we should ditch inline-editing for now, and show a link to preview.

I know this is how github handles it - rendered when viewing, not rendered when editing, and I hate that

Maybe we should do some user research?

**Comment by duncangraham** [comment]
what if it was a toggle, but clicking the body text reversed the toggle and went back into editing mode? 

I think our own opinions and feelings are a pretty good metric (WRT user research). If something feels shitty, we shouldn't do it and should find a behavior/workflow that makes us feel happy @jshawl

**Comment by jshawl** [comment]
ok for now, I want to move forward by implementing a toggle.

Clicking "preview" shows rendered markdown without option to edit. Clicking edit shows codemirror (unrendered markdown) - thoughts?

**Comment by duncangraham** [comment]
when you say unrendered markdown-- you mean the markdown we have currently, right? I kinda like the style, and the hints toward what it looks like rendered.

Other than that, yea I'm a :+1:

**Comment by jshawl** [comment]
shipped! 62e7bde
