### ISSUE TITLE
Trying to save a new gist hangs

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#109]
when there is no change/contents to/in the codemirror/body section

(overdid that with back slashes, no regrets.)

**Comment by jshawl** [comment]
Should we allow empty gist creation? or force the user to enter content in the textarea?

**Comment by duncangraham** [comment]
I'm fine with either, I'd say allow it. If you think it makes sense not to, then we need to make an error state letting the user know why they can't save the document
