### ISSUE TITLE
Buttons are too inconsistent

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#116]
I don't know what ticket your changes were tied to, but the buttons are more confusing for me now.

I think the old version where "Your gists" + "New gists" were constantly on the left and "delete" + "save" were on the right was way more clear. 

now it seems like every view has a custom ordering of buttons. makes it difficult to use them, since they're rearranged.

**Comment by duncangraham** [comment]
## Your gists

**Master**
![screen shot 2015-04-17 at 2 04 48 am](https://cloud.githubusercontent.com/assets/865298/7199028/2b947b94-e4a6-11e4-8e8d-6df2415cea85.png)

**Button-pos branch fix**
![screen shot 2015-04-17 at 2 04 32 am](https://cloud.githubusercontent.com/assets/865298/7199033/37c5e5f6-e4a6-11e4-8538-7817dac2424c.png)

**Comment by duncangraham** [comment]
before i change more, I'm betting this was done for the mobile use case. I think there's gotta be a strategy to make the nav on both mobile and desktop clear and user-friendly

**Comment by jshawl** [comment]
Yes! it was to keep button position consistent for submit feedback and view on github.

I think one thing we could do is move the buttons that are in every view over by the logo:
- your gists
- new gist
- submit feedback
- logout

And only have the buttons related to the current gists as fixed to the bottom:
- edit 
- save
- delete
- preview
- view on github

What do you think?

**Comment by duncangraham** [comment]
I'm hesitant to break the column container rule i've been following. I like breaking the rule once with the logo, it sets the logo apart. Doing it more than once decreases the importance of the logo and makes it easier to break it in the future. I don't think that it's necessary to break the rule in this case for legibility/usefulness. (if the button strategy below doesn't fit in the space though i'll bend my rules or think of a third path)

lets put
- your gists
- new gist (on the far left)
- submit feedback
- logout

on the left side of the column

and 
- edit 
- save (on the far right. most prominent location)
- delete
- preview
- view on github

on the right side. That's a clear and understandable divide.

## what do you think of this layout?

New Gist | Your Gist | Feedback? | Logout______________view on (github icon) | preview | delete | save

**Comment by duncangraham** [comment]
![screen shot 2015-04-24 at 12 50 07 pm](https://cloud.githubusercontent.com/assets/865298/7327241/8240d0b6-ea80-11e4-9688-1769eb31cad5.png)

this is the button layout on the 'your gists' view. I removed the 'your gists' button since people are already on that page. everything is right aligned, so after clicking 'login with github' similar buttons (like logout) are in the same location. i <3 this consistency.

![screen shot 2015-04-24 at 12 52 47 pm](https://cloud.githubusercontent.com/assets/865298/7327287/d51295e0-ea80-11e4-9d84-42f3794b060a.png)

on the 'show' view, the buttons associated with the gist are on the left, with 'save; at the most hierarchical, far-left location. on the right, a 'your gists' option is added, but the ordering of the buttons don't change.

**Comment by jshawl** [comment]
aw hell yeah this is  :star: nice!!
