### ISSUE TITLE
how should we handle public vs private?

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#16]

**Comment by jshawl** [comment]
Already done! (I think) Privacy for gists is - anyone with the link can view. Since there is no interface on gistalt.co to browse user's gists, we don't have to worry about this, _but_ I can explicitly share a secret one, like - http://gistalt.co/36c20519a9d5fbcd5558/2015-03-22.md

**Comment by duncangraham** [comment]
true true
