### ISSUE TITLE
fork/edit

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#3]

**Comment by jshawl** [comment]
There are a couple of ways to implement fork/edit, what do you think?

1) User is allowed to edit even if not logged in. When user clicks update, redirect to login, fork the gist, update the fork gist, redirect to user's gist.

2) User is not allowed to edit gists unless owner. User clicks "fork" button, and is redirected to their fork.

**Comment by jshawl** [comment]
re #6 it seems like option 2 is a closer fit to the wireframe - i like it!

**Comment by jshawl** [comment]
implemented in https://github.com/jshawl/gizt/commit/5b3862fc4794f1aeed37979069d80cb66ada788b
