### ISSUE TITLE
submit feedback should not leave gistalt.co

### ISSUE THREAD

**Issue by jshawl** [jshawl/gistalt#32]
instead of linking to github new issue, what if show the "new" view and programmatically submit an issue. The UI will be nicer and people won't leave gistalt.co

**Comment by duncangraham** [comment]
you think this is better? if we link to github then people can see the code/that its built in the open and can contribute themselves

**Comment by jshawl** [comment]
True lets postpone this

On Monday, April 6, 2015, duncangraham notifications@github.com wrote:

> you think this is better? if we link to github then people can see the
> code/that its built in the open and can contribute themselves
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jshawl/gistalt/issues/32#issuecomment-90283703.

## 

Jesse Shawl
http://jshawl.com
