### ISSUE TITLE
logging in throws an error?

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#33]
or at least it's going to http://localhost:4000/undefined

**Comment by duncangraham** [comment]
probably a bug i introduced on the home page log in with github button

**Comment by jshawl** [comment]
I was unable to reproduce this locally. Also, I reverted this commit, but added to a new branch - `next`. 

You can continue working on this by

```
$ git fetch origin next
$ git checkout -b next origin/next
```
