### ISSUE TITLE
Shared gistalt page needs <3

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#39]
when you're not logged in, a shared gistalt is really not good looking

http://gistalt.co/078729ee16ab264caca8/2015-04-08.md
![screen shot 2015-04-08 at 6 29 25 pm](https://cloud.githubusercontent.com/assets/865298/7058925/41c82a08-de1d-11e4-9feb-07b1931bf899.png)

the codemirror is really small and scroll-y and theres no info on what gistalt is or how to use/login

**Comment by jshawl** [comment]
fixed the really small part
