### ISSUE TITLE
add inline editing

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#4]
![screen shot 2015-03-15 at 11 45 21 am](https://cloud.githubusercontent.com/assets/865298/6656949/ce104bb2-cb08-11e4-9a8d-6a3764e03a83.png)

**Comment by jshawl** [comment]
https://stackedit.io/editor

**Comment by jshawl** [comment]
http://sofish.github.io/pen/

**Comment by duncangraham** [comment]
why was this closed?

**Comment by jshawl** [comment]
We have to choose between inline editing and code mirror. Ditching code
mirror is still an option!

On Tuesday, April 14, 2015, duncangraham notifications@github.com wrote:

> why was this closed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gistalt/gistalt/issues/4#issuecomment-93048998.

## 

Jesse Shawl
http://jshawl.com

**Comment by duncangraham** [comment]
I don't think it has to be a choice, does it? I think this inline editing would be an option when viewing in preview mode. if that's out of scope (or not aligned with gistalt's goal/purpose) feel free to close @jshawl

**Comment by jshawl** [comment]
I like that the preview is uneditable - it also means we can reuse those views for logged out users. Let's hear what the users think.
