### ISSUE TITLE
Hitting enter while changing the title => 502

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#44]
after or during changing the title, if you hit enter you get a 502 bad gateway error at the URL http://gistalt.co/undefined/end.md

you're then logged out and trying to log in throws the same error. you can only log in by manually going to the home page.

![screen shot 2015-04-09 at 11 12 18 am](https://cloud.githubusercontent.com/assets/865298/7073623/9ef2aa78-dea9-11e4-9b21-7a29f9e6601b.png)

**Comment by jshawl** [comment]
note to future jesse: override form submit, trigger data-submit click
