### ISSUE TITLE
Add logo which links to the homepage

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#45]
I realized with https://github.com/jshawl/gistalt/issues/44 that not being able to go to the home page is shitty. I'll make a logo for this (its funny that my design itch to do this never kicked in)

I'm thinking that on hover the "made with love by jesse and duncan" will show up

**Comment by jshawl** [comment]
:+1:

**Comment by duncangraham** [comment]
![screen shot 2015-04-11 at 6 58 36 pm](https://cloud.githubusercontent.com/assets/865298/7104092/d99899f6-e07c-11e4-94c1-8d07485588b6.png)

started digital explorations. way too stretched on the x axis now

**Comment by jshawl** [comment]
please ship this :star2: :+1:

**Comment by duncangraham** [comment]
![screen shot 2015-04-11 at 7 19 49 pm](https://cloud.githubusercontent.com/assets/865298/7104134/be8f5d2c-e07f-11e4-98a2-6c7a6f359456.png)

v2

**Comment by duncangraham** [comment]
![screen shot 2015-04-11 at 7 25 02 pm](https://cloud.githubusercontent.com/assets/865298/7104144/7ba9f9f8-e080-11e4-9d4a-99ace1d718a0.png)

continuing to iterate

**Comment by jshawl** [comment]
:+1:

**Comment by duncangraham** [comment]
merged https://github.com/jshawl/gistalt/pull/67
