### ISSUE TITLE
change public checkbox to more prominent toggle

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#49]
and it continues to drive my designer brain insane

![screen shot 2015-04-09 at 2 41 04 pm](https://cloud.githubusercontent.com/assets/865298/7077551/8c8dbd4c-dec6-11e4-878a-43b2afc862b7.png)

I'll center it

**Comment by duncangraham** [comment]
was thinking about this, and the checkbox is tiny on mobile. Makes sense to make it a more clear button, right?

**Comment by duncangraham** [comment]
![screen shot 2015-04-11 at 5 58 34 pm](https://cloud.githubusercontent.com/assets/865298/7103948/913b195c-e074-11e4-9313-8fa7218edf36.png)

what it looks like now, though its not programmatically hooked up to anything.

should I write a $.trigger in the Gistalt object @jshawl? whats the best way of getting a non form element working with something in the form?

**Comment by jshawl** [comment]
It's impossible to toggle public/private via the api.

As a workaround? We could just create a new gist with the current gists
contents

On Saturday, April 11, 2015, duncangraham notifications@github.com wrote:

> [image: screen shot 2015-04-11 at 5 58 34 pm]
> https://cloud.githubusercontent.com/assets/865298/7103948/913b195c-e074-11e4-9313-8fa7218edf36.png
> 
> what it looks like now, though its not programmatically hooked up to
> anything.
> 
> should I write a $.trigger in the Gistalt object @jshawl
> https://github.com/jshawl? whats the best way of getting a non form
> element working with something in the form?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jshawl/gistalt/issues/49#issuecomment-91956743.

## 

Jesse Shawl
http://jshawl.com

**Comment by duncangraham** [comment]
@jshawl this is just for new gists, my bad for not makin that clear

**Comment by jshawl** [comment]
Oh!

I would first add a reference to it: https://github.com/jshawl/gistalt/blob/a98c1b24d622793df3694b25bb99c02c2e79d0b5/public/js/app.js#L3

then set up an event listener to toggle the checkbox - https://github.com/jshawl/gistalt/blob/a98c1b24d622793df3694b25bb99c02c2e79d0b5/public/js/app.js#L60

**Comment by duncangraham** [comment]
![toggle](https://cloud.githubusercontent.com/assets/865298/7104962/d2518b5a-e0b6-11e4-888b-10d790c6ae8d.gif)

theres a demo of the new toggle states, but when I was testing I noticed that not adding any text to the gist caused the save to hang, and saving at all prompts the onbeforeunload function (which shouldn't happen on /new)
