### ISSUE TITLE
make description mobile styling work on desktop

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#56]
It looks like in this commit the description made the gist header look like this

![screen shot 2015-04-10 at 1 54 37 pm](https://cloud.githubusercontent.com/assets/865298/7097354/ab771a00-df89-11e4-9dff-9b5946f428b5.png)

is this intentional @jshawl? the metadata seems out of place

https://github.com/jshawl/gistalt/commit/12fe04d8f1912545055988bf9daf0094cb9e1b75#diff-8203f7eb857fb4b4b5603c7e1b84f009

**Comment by jshawl** [comment]
before, the input was cut off. This code should be in a media query

**Comment by duncangraham** [comment]
cool, renaming
