### ISSUE TITLE
Mobile buttons

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#57]
Having buttons at the top sux. in general our button strategy on mobile is nonexistent. 

lets move them to the bottom of the screen, and stack them by importance.

![screen shot 2015-04-10 at 1 57 14 pm](https://cloud.githubusercontent.com/assets/865298/7097417/4d41dcd0-df8a-11e4-9b4d-d748be6dacfb.png)

we can also change the view on github to the github icon (also, maybe a logout icon?). we can change new to '+New'.

Last thing, @jshawl do you know if we can we hide buttons if the keyboard is open? does this make sense? I figure that if i'm typing I'm probably not doing high level button stuff.

**Comment by jshawl** [comment]
can we keep the buttons relatively positioned for mobile? Feel like sticky takes up too much screen real estate.

also, I think the keyboard will cover the buttons - but programmatically hiding them seems difficult to maintain
