### ISSUE TITLE
bottom buttons aren't aligned to the grid

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#59]
![screen shot 2015-04-11 at 12 10 51 pm](https://cloud.githubusercontent.com/assets/865298/7102829/de3458f8-e043-11e4-85ac-42b72bbc794e.png)

**Comment by duncangraham** [comment]
figured out its

```
[role="main"] {
  padding: 1em 1em 6em 1em;
}
```

that's doing this. digging to see what this is supposed to do

**Comment by duncangraham** [comment]
@jshawl looks like it was introduced here-- https://github.com/jshawl/gistalt/commit/06c80ddd8b3a3ea44ead5653b638d548f2dc4d8f#diff-8203f7eb857fb4b4b5603c7e1b84f009R135

what's this doing?

**Comment by jshawl** [comment]
Adds space vertically to show pagination links, adds space horizontally so
text doesn't touch screen edge on mobile

On Saturday, April 11, 2015, duncangraham notifications@github.com wrote:

> @jshawl https://github.com/jshawl looks like it was introduced here--
> 06c80dd#diff-8203f7eb857fb4b4b5603c7e1b84f009R135
> https://github.com/jshawl/gistalt/commit/06c80ddd8b3a3ea44ead5653b638d548f2dc4d8f#diff-8203f7eb857fb4b4b5603c7e1b84f009R135
> 
> what's this doing?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jshawl/gistalt/issues/59#issuecomment-91908735.

## 

Jesse Shawl
http://jshawl.com
