### ISSUE TITLE
wireframes

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#6]
![screen shot 2015-03-15 at 12 41 55 pm](https://cloud.githubusercontent.com/assets/865298/6657162/af900364-cb10-11e4-829f-ca2f95330b8d.png)

quick sketch. have to work more, add the menu open state, and the new gist button and view

**Comment by duncangraham** [comment]
not a fan of the "fork and save" location. If i'm halfway scrolled down then it wouldn't show up, unless a menu popped up (which i don't like much)

**Comment by jshawl** [comment]
what about a sticky menu on the left?

**Comment by jshawl** [comment]
also is this in code? if so can you push a branch

**Comment by duncangraham** [comment]
working on a style branch now, pushing soon @jshawl

**Comment by duncangraham** [comment]
So here are my early thoughts on what think the home page should be:

rather than making a standalone page, I think it would be awesome to use the gistalt interface to show a gist that acts as the homepage. Let people edit inline, fork this gist, show off the features etc.

![screen shot 2015-03-17 at 11 12 37 am](https://cloud.githubusercontent.com/assets/865298/6691844/016a68be-cc97-11e4-9e9f-6a25d7009e50.png)

_I played around with the menu a bunch, adding the view on github in line with the gistalt, but I think making it really stripped down and shoving  it in the right hand corner is the best bet for now (we can iterate later)_

I want the "new and your gists" options more prominent so people choose to authenticate with github off the bat. If these exist, should there even be a sign in with github option? It would be more apparent, but lets user test.

after authenticating, it will either go to a new screen or open to their most recent gist.

## 

Another (I think more likely) possibility is that they choose to mess around and edit Gistalt.md, after which the Fork and Save option will change from gray to blue to grab attention

![screen shot 2015-03-17 at 11 15 21 am](https://cloud.githubusercontent.com/assets/865298/6691828/ed9ab91a-cc96-11e4-9531-60a4febfcd73.png)

## 

If I am editing, I would love to have automatic saving enabled. if I pause my typing I'd love to get these two screens working

![screen shot 2015-03-17 at 11 21 18 am](https://cloud.githubusercontent.com/assets/865298/6691966/cf00e2d0-cc97-11e4-86f8-9a30a2795398.png)
![screen shot 2015-03-17 at 11 21 32 am](https://cloud.githubusercontent.com/assets/865298/6691967/cf0f25ca-cc97-11e4-8728-79b10a4384b6.png)
![screen shot 2015-03-17 at 11 23 04 am](https://cloud.githubusercontent.com/assets/865298/6692005/0a29903c-cc98-11e4-9066-cc13bbe324ff.png)
_not sure about the last view... does it make sense to have a force save option?_

**Comment by jshawl** [comment]
Styles look awesome! Can you submit your layout changes as an MVP and we'll keep iterating? (i.e. remove breaking changes?)
