### ISSUE TITLE
logging in goes to /undefined

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#60]
![screen shot 2015-04-11 at 12 25 03 pm](https://cloud.githubusercontent.com/assets/865298/7102899/d40fb4c4-e045-11e4-8434-f83d4fec748a.png)

can you recreate this bug @jshawl?

**Comment by jshawl** [comment]
Yes!! But only 1/10 log ins. Will try to systematically reproduce.

On Saturday, April 11, 2015, duncangraham notifications@github.com wrote:

> Assigned #60 https://github.com/jshawl/gistalt/issues/60 to @jshawl
> https://github.com/jshawl.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jshawl/gistalt/issues/60#event-278898275.

## 

Jesse Shawl
http://jshawl.com

**Comment by duncangraham** [comment]
this is only happening right after I run gulp for the first time

![undefined](https://cloud.githubusercontent.com/assets/865298/7102908/45416f5c-e046-11e4-9a3f-94fa0d579ff6.gif)

**Comment by jshawl** [comment]
There must be something else:

![login-undefined-bug](https://cloud.githubusercontent.com/assets/3824954/7102916/cb24a030-e05f-11e4-993a-21b5f2f56f8f.gif)
