### ISSUE TITLE
style delete button

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#75]
right now the delete button is bright red, and interferes with the pulsing save button

**Comment by jshawl** [comment]
closing - changed to salmon in 33ba27f. feel free to reopen

**Comment by duncangraham** [comment]
yea, salmon is nice, but it still seems strange when next to the red pulsing save button

**Comment by duncangraham** [comment]
the delete button is now the same gray as the other buttons, but on hover it turns to the salmon color.

I think this is better because 
1. it doesn't visually interfere when the save button turns salmon to show unsaved changes
2. the delete button doesn't hierarchically need its own constant color
3. the hover state gives enough feedback (though mobile may be a different story)

**Comment by jshawl** [comment]
:+1: Looks good! I like that it's not screaming at me anymore.
