### ISSUE TITLE
gist ID in URL, gist title in views

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#8]
rather than using the gist ID in the views, can we use the gist titles? 

**Wins**
- cut out the step from clicking the gist ID, then clicking the title. 
- a list of IDs isn't as readable as a list of human titles

**Comment by jshawl** [comment]
The gist id is the unique identifier for the contents on github, so it has to be in the url.

Also, gists have descriptions (but not titles), and they are optional.

We could change the format to only create gists and view gists created from this app.

with that we could require a title for a gist. Then we could get rid of the gist id and use gist titles in the url.

**Comment by jshawl** [comment]
actually if we get rid of the gist id, then users won't be able to share their posts on this site.

i.e. what would be the difference between your readme.md and my readme.md
