### ISSUE TITLE
share page should have a share button

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#82]
the page which links to a gist should have ways to continue sharing (tweets, fb posts, etc)

i'm shaky on this. like, why not just copy the URL and share that?

**Comment by jshawl** [comment]
share buttons feel intrusive to me - will users not share a page without a share button?

**Comment by jshawl** [comment]
actual question - fairly certain a button will increase the shares

**Comment by duncangraham** [comment]
if it's only on another users gist (whether or not you're logged in), i think a share button might make sense _if the gist is public_

if its private, than a share button seems counter to the intent. 

with that said, I'm not sold that sharing is why we built this, or a necessary (or useful) feature. lets let people use URLs for now. If we get a lot of feature requests we can change the game plan
