### ISSUE TITLE
on hover over link in markdown cursor=pointer

### ISSUE THREAD

**Issue by duncangraham** [jshawl/gistalt#92]
and maybe a tooltip that says 'open in new window'

**Comment by duncangraham** [comment]
![screen shot 2015-04-13 at 10 43 29 pm](https://cloud.githubusercontent.com/assets/865298/7131023/b191ec92-e22e-11e4-8c97-ec4f262f97ee.png)

**Comment by duncangraham** [comment]
clicking on these spans should then open that link in a new page

**Comment by jshawl** [comment]
What is the difference between clicking on something to edit it, and clicking on something to open the link?

**Comment by duncangraham** [comment]
hahaha oh shit. duh.
